//! Serving the embedded operator UI — ARC-02, USB-09/10, SDD §5.9. This is the M0-T06 half of the
//! static-asset seam described in [`crate::api`].
//!
//! # Two subtrees, one origin, one auth policy each
//!
//! [`router`] is merged *outside* the bearer-auth layer, and it has to be: a browser cannot put an
//! `Authorization` header on the navigation request that loads an app shell. The shell is
//! therefore public and the API is not, which is safe because the shell is a static bundle that
//! knows nothing — every fact it displays comes from a request the operator's token has to carry.
//!
//! # What happens to an API path that matches no route
//!
//! Merging an unauthenticated fallback under `/` is where this could quietly undo a property
//! M0-T05 established: auth sits outside routing so that "the token is wrong" and "that path does
//! not exist" are indistinguishable, and an unauthenticated caller cannot map the API by probing.
//! A fallback that returned the app shell for `/api/mount/position` would give that away — 200
//! HTML for a path that does not exist, 401 for one that does.
//!
//! So this fallback does not serve the shell for API-shaped paths. It re-runs the same
//! [`AuthPolicy::authorize`] the layer runs and renders the same 401 through the same function
//! ([`crate::auth::unauthorized`]) — identical by construction rather than by two copies staying
//! in step — and only answers 404 to a caller that has already proved it may know the difference.
//!
//! # Absent bundle
//!
//! `frontend/dist` is generated by npm and git-ignored, so it is missing from every fresh clone.
//! `build.rs` sets `cfg(pwa_embedded)` when it exists; without it this module compiles a
//! placeholder page instead, and `cargo build -p astroctl-field` works with no Node toolchain
//! anywhere on the machine.

use std::sync::Arc;

use astroctl_core::error::{ApiError, ErrorCode};
use axum::body::Body;
use axum::extract::{Request, State};
use axum::http::{header, Method};
use axum::response::{IntoResponse, Response};
use axum::Router;

use astroctl_core::config::DeploymentLabel;
use serde_json::json;

use crate::api::ApiFailure;
use crate::auth::AuthPolicy;
use crate::proxy;

/// The built PWA, compiled into the binary (ARC-02: "the compiled bundle is served as static
/// files, so deployment is a single service").
#[cfg(pwa_embedded)]
static DIST: include_dir::Dir<'static> =
    include_dir::include_dir!("$CARGO_MANIFEST_DIR/../../frontend/dist");

/// Path prefixes that belong to the API rather than to the UI.
///
/// `/ws` is here before the WS hub exists (M1-T03) on purpose: an upgrade request that fell
/// through to the SPA fallback would receive `index.html` with a 200, and a browser waiting for a
/// handshake it will never get is a hang with no error anywhere to explain it.
const API_PREFIXES: &[&str] = &["/api", proxy::PREFIX, "/ws"];

/// The unauthenticated static subtree: no routes, one fallback.
///
/// A fallback rather than a route per asset because the SPA needs one anyway — every client-side
/// route (`/target`, `/frame`, `/stack` in M1) has to resolve to `index.html`, and there is no
/// list of them a server could hold.
pub fn router(auth: Arc<AuthPolicy>, deployment: Option<DeploymentLabel>) -> Router {
    Router::new()
        .fallback(serve)
        .with_state(PwaState { auth, deployment })
}

/// What the static subtree needs: who may call the API, and which deployment this is.
#[derive(Clone)]
struct PwaState {
    auth: Arc<AuthPolicy>,
    /// `None` is production. See [`manifest`] for why this reaches the manifest at all.
    deployment: Option<DeploymentLabel>,
}

async fn serve(State(state): State<PwaState>, request: Request) -> Response {
    let path = request.uri().path();

    if API_PREFIXES.iter().any(|prefix| under(path, prefix)) {
        return api_miss(&state.auth, &request);
    }

    // Generated rather than served from the bundle, so one binary and one `dist/` can be a dev
    // node or a production node according to config alone.
    if path == "/manifest.webmanifest" && request.method() == Method::GET {
        return manifest(state.deployment.as_ref());
    }

    // The shell is a document. A POST to `/anything` is not a mis-typed URL, it is a client
    // calling an endpoint that does not exist, and answering it with HTML would let that mistake
    // reach whatever parses the response.
    if request.method() != Method::GET && request.method() != Method::HEAD {
        return not_found("the operator UI is served over GET; this is not an API path");
    }

    shell(path)
}

/// `path` is `prefix` itself or something beneath it — but not `/apixyz`.
fn under(path: &str, prefix: &str) -> bool {
    path == prefix
        || path
            .strip_prefix(prefix)
            .is_some_and(|rest| rest.starts_with('/'))
}

/// The PWA manifest, built from config rather than served from the bundle.
///
/// # Why this is generated
///
/// A PWA's install identity is keyed by **origin**, so a dev node on its own hostname already
/// installs beside production with its own service worker, cache and `localStorage`. The origin
/// does not make the two *distinguishable* once installed, though: without this, both appear as
/// "AstroCtl" with the same icon, and one of them drives a real mount. Generating the manifest
/// lets one binary and one `dist/` serve either deployment, chosen by `server.deployment_label`,
/// instead of maintaining two builds that will drift.
///
/// `id` stays `/` in both. It is resolved against the origin, and the origins already differ —
/// giving the dev node a different `id` would buy nothing and would silently orphan an installed
/// app the first time someone changed the label.
fn manifest(deployment: Option<&DeploymentLabel>) -> Response {
    let (name, icon_prefix) = match deployment {
        Some(label) => (format!("AstroCtl {}", label.as_str()), "icon-dev"),
        None => ("AstroCtl".to_owned(), "icon"),
    };
    let icon = |size: u32, purpose: &str, suffix: &str| {
        json!({
            "src": format!("/icons/{icon_prefix}-{suffix}.png"),
            "sizes": format!("{size}x{size}"),
            "type": "image/png",
            "purpose": purpose,
        })
    };
    let body = json!({
        "id": "/",
        "name": name,
        "short_name": name,
        "description": "Field control for a remote astrophotography rig.",
        "start_url": "/",
        "scope": "/",
        "display": "standalone",
        "orientation": "any",
        "background_color": "#000000",
        "theme_color": "#000000",
        "categories": ["utilities", "productivity"],
        "icons": [
            icon(192, "any", "192"),
            icon(512, "any", "512"),
            icon(512, "maskable", "maskable-512"),
        ],
    });
    (
        [
            (header::CONTENT_TYPE, "application/manifest+json"),
            // Chrome re-reads the manifest to notice an identity change. A cached one would keep
            // an installed app named after the deployment it used to be.
            (header::CACHE_CONTROL, "no-cache"),
        ],
        body.to_string(),
    )
        .into_response()
}

/// An API-shaped path that matched no declared route. See the module docs.
fn api_miss(auth: &AuthPolicy, request: &Request) -> Response {
    if let Err(error) = auth.authorize(request.headers()) {
        return crate::auth::unauthorized(&error);
    }
    // The path is deliberately not echoed. It is caller-controlled text, and `/api/system/info`
    // publishes the whole route table to anyone entitled to see this response anyway (SDD §8.2),
    // which is a better answer than a reflection of what they just typed.
    not_found("no such route on this node; GET /api/system/info publishes the route table")
}

fn not_found(message: &'static str) -> Response {
    ApiFailure(ApiError::new(ErrorCode::NotFound, message)).into_response()
}

// ---------------------------------------------------------------------------------------------
// The bundle
// ---------------------------------------------------------------------------------------------

#[cfg(pwa_embedded)]
fn shell(path: &str) -> Response {
    // `include_dir` resolves against an in-memory index built at compile time, so a `..` in the
    // request addresses nothing rather than escaping to the filesystem — there is no filesystem
    // in this lookup to escape to.
    //
    // The path is not percent-decoded. Every name Vite emits is ASCII and hash-derived, so there
    // is nothing to decode; if that ever stops being true the symptom is an asset 404 that falls
    // through to the shell, which is visible immediately rather than subtly wrong.
    let relative = path.trim_start_matches('/');
    match DIST.get_file(relative) {
        Some(file) => asset(relative, file.contents()),
        // The SPA fallback: any path that is not a file is a client-side route.
        None => index(),
    }
}

#[cfg(pwa_embedded)]
fn index() -> Response {
    match DIST.get_file("index.html") {
        Some(file) => asset("index.html", file.contents()),
        // Unreachable: build.rs only sets `pwa_embedded` when `frontend/dist/index.html` exists.
        None => ApiFailure(ApiError::new(
            ErrorCode::Internal,
            "the embedded UI bundle has no index.html",
        ))
        .into_response(),
    }
}

#[cfg(pwa_embedded)]
fn asset(path: &str, bytes: &'static [u8]) -> Response {
    (
        [
            (header::CONTENT_TYPE, content_type(path)),
            (header::CACHE_CONTROL, cache_control(path)),
        ],
        // `from_static` rather than a copy: the bytes are in the binary's read-only data and the
        // body borrows them, so serving a 200 KB bundle to ten clients allocates nothing.
        Body::from(axum::body::Bytes::from_static(bytes)),
    )
        .into_response()
}

/// Media type by extension.
///
/// A table rather than a `mime_guess` dependency: the set of extensions a Vite build emits is
/// small, known, and changes when someone adds an asset kind on purpose. `application/octet-stream`
/// for anything else is the safe default — a browser will not execute what it cannot identify.
#[cfg(pwa_embedded)]
fn content_type(path: &str) -> &'static str {
    match path.rsplit_once('.').map(|(_, extension)| extension) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json") => "application/json",
        // Chrome will not treat the file as a manifest under any other type, and the install
        // prompt (USB-09) simply never appears.
        Some("webmanifest") => "application/manifest+json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("ico") => "image/x-icon",
        Some("woff2") => "font/woff2",
        Some("txt") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

/// How long a browser may keep a file without asking.
///
/// Everything under `/assets/` carries a content hash in its name, so it can be cached forever:
/// a change produces a different name. Everything else must be revalidated, and `sw.js` is the
/// reason this matters rather than a nicety — a service worker cached at the HTTP layer is one
/// that cannot be replaced until the cache expires, which makes a bad worker unfixable remotely
/// on a machine at the end of a VPN.
#[cfg(pwa_embedded)]
fn cache_control(path: &str) -> &'static str {
    if path.starts_with("assets/") {
        "public, max-age=31536000, immutable"
    } else {
        "no-cache"
    }
}

// ---------------------------------------------------------------------------------------------
// No bundle
// ---------------------------------------------------------------------------------------------

/// What `/` serves when the binary was built without `frontend/dist`.
///
/// 200, not 503. The node is not degraded: every API route works, the watchdogs run, and a
/// container health check pointed at this binary is telling the truth when it says the service is
/// up. The missing thing is a browser bundle, and the only party who needs to know is the person
/// reading this page.
///
/// It carries no colours — `color-scheme: dark` is enough to keep it from flashing white at
/// someone at 2 a.m. — because a literal palette here would be a second, unmaintained copy of the
/// token layer that nobody would think to update.
#[cfg(not(pwa_embedded))]
fn shell(_path: &str) -> Response {
    const PAGE: &str = concat!(
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">",
        "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">",
        "<title>AstroCtl — operator UI not built</title>",
        "<style>:root{color-scheme:dark}body{font:1rem/1.6 system-ui,sans-serif;",
        "margin:0;min-height:100dvh;display:grid;place-items:center;padding:2rem}",
        "main{max-width:36rem}code,pre{font-family:ui-monospace,monospace}",
        "pre{padding:1rem;border:1px solid;border-radius:.5rem;overflow-x:auto}</style>",
        "</head><body><main>",
        "<h1>The operator UI is not in this binary</h1>",
        "<p>This <code>astroctl-field</code> was built without <code>frontend/dist</code>, so ",
        "there is no PWA to serve. The API is unaffected — <code>/api/system/health</code> and ",
        "<code>/api/system/info</code> answer normally.</p>",
        "<pre>scripts/build-frontend.sh\ncargo build -p astroctl-field</pre>",
        "<p>The bundle is git-ignored and generated by npm, so a fresh clone always starts here. ",
        "Building it is not part of <code>cargo build</code> on purpose: nobody working on the ",
        "Rust side should need a Node toolchain to run the tests.</p>",
        "</main></body></html>"
    );

    (
        [
            (header::CONTENT_TYPE, "text/html; charset=utf-8"),
            (header::CACHE_CONTROL, "no-store"),
        ],
        Body::from(PAGE),
    )
        .into_response()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api;
    use crate::test_support::{state_with, TestNode};
    use axum::body::to_bytes;
    use axum::http::{header, HeaderValue, Request, StatusCode};
    use serde_json::Value;
    use tower::ServiceExt as _;

    struct Answer {
        status: StatusCode,
        content_type: String,
        cache_control: String,
        body: Vec<u8>,
    }

    impl Answer {
        fn text(&self) -> String {
            String::from_utf8_lossy(&self.body).into_owned()
        }

        fn json(&self) -> Value {
            serde_json::from_slice(&self.body).unwrap_or(Value::Null)
        }
    }

    /// Drive the *assembled* application — the API with its auth layer plus this router merged
    /// onto it — because everything interesting here is a property of the merge, not of either
    /// half. `crate::assemble` is the same function `main` calls.
    async fn call(node: &TestNode, method: Method, path: &str, token: Option<&str>) -> Answer {
        let (router, declarations) = api::router();
        let state = state_with(node, declarations);
        let app = crate::assemble(router, state);

        let mut request = Request::builder().method(method).uri(path);
        if let Some(token) = token {
            request = request.header(header::AUTHORIZATION, format!("Bearer {token}"));
        }
        let response = app
            .oneshot(request.body(Body::empty()).expect("request builds"))
            .await
            .expect("router responds");

        let status = response.status();
        let headers = response.headers().clone();
        let read = |name: header::HeaderName| {
            headers
                .get(name)
                .and_then(|v| v.to_str().ok())
                .unwrap_or_default()
                .to_owned()
        };
        Answer {
            status,
            content_type: read(header::CONTENT_TYPE),
            cache_control: read(header::CACHE_CONTROL),
            body: to_bytes(response.into_body(), 8 << 20)
                .await
                .expect("body reads")
                .to_vec(),
        }
    }

    async fn get(node: &TestNode, path: &str, token: Option<&str>) -> Answer {
        call(node, Method::GET, path, token).await
    }

    // --- the merge must not weaken M0-T05's auth posture -------------------------------

    /// The property M0-T05 built the middleware order for, re-asserted against the assembled app:
    /// an unauthenticated caller cannot tell a route that exists from one that does not.
    ///
    /// Without the API-prefix branch in [`serve`] this test fails by returning 200 and an HTML
    /// shell for `/api/mount/position`, which is exactly the leak the module docs describe.
    #[tokio::test]
    async fn an_undeclared_api_path_is_indistinguishable_from_a_declared_one_without_a_token() {
        let node = TestNode::authenticated("s3cret");
        for path in [
            "/api/system/health",
            "/api/mount/position",
            "/api/does/not/exist",
            "/stack/api/system/health",
            "/stack/nope",
            "/ws/events",
        ] {
            let answer = get(&node, path, None).await;
            assert_eq!(answer.status, StatusCode::UNAUTHORIZED, "for {path}");
            assert_eq!(answer.json()["code"], "AUTH", "for {path}");
        }
    }

    /// …and a caller that *has* proved itself gets the honest answer instead.
    #[tokio::test]
    async fn an_undeclared_api_path_is_404_once_the_token_is_valid() {
        let node = TestNode::authenticated("s3cret");
        let answer = get(&node, "/api/mount/position", Some("s3cret")).await;
        assert_eq!(answer.status, StatusCode::NOT_FOUND);
        assert_eq!(answer.json()["code"], "NOT_FOUND");
        assert_eq!(answer.json()["retryable"], false);
    }

    /// The manifest is public: the install machinery fetches it with no credentials, so a 401
    /// here would mean the app could never be installed at all.
    #[tokio::test]
    async fn the_manifest_is_served_without_a_token() {
        let node = TestNode::authenticated("s3cret");
        let answer = get(&node, "/manifest.webmanifest", None).await;
        assert_eq!(answer.status, StatusCode::OK);
        assert_eq!(answer.content_type, "application/manifest+json");
        assert_eq!(answer.json()["name"], "AstroCtl");
        assert_eq!(answer.json()["icons"][0]["src"], "/icons/icon-192.png");
    }

    /// The point of generating it: one binary and one bundle, two installable identities.
    #[tokio::test]
    async fn a_labelled_deployment_gets_its_own_name_and_icons() {
        let node = TestNode::authenticated("s3cret").with_deployment_label("Dev");
        let answer = get(&node, "/manifest.webmanifest", None).await;

        assert_eq!(answer.json()["name"], "AstroCtl Dev");
        assert_eq!(answer.json()["icons"][0]["src"], "/icons/icon-dev-192.png");
        assert_eq!(answer.json()["icons"][2]["purpose"], "maskable");

        // `id` and `scope` must NOT vary: they are resolved against the origin, which already
        // differs, and changing `id` orphans an app that is already on someone's home screen.
        assert_eq!(answer.json()["id"], "/");
        assert_eq!(answer.json()["scope"], "/");
    }

    /// Chrome re-reads the manifest to notice a rename. A cached one leaves an installed app
    /// wearing the name of the deployment it used to be.
    #[tokio::test]
    async fn the_manifest_is_not_cached() {
        let node = TestNode::authenticated("s3cret");
        assert_eq!(
            get(&node, "/manifest.webmanifest", None)
                .await
                .cache_control,
            "no-cache"
        );
    }

    /// The declared routes keep working through the merge — the layer is still on them.
    #[tokio::test]
    async fn the_api_still_serves_and_still_requires_its_token_after_the_merge() {
        let node = TestNode::authenticated("s3cret");
        let answer = get(&node, "/api/system/health", Some("s3cret")).await;
        assert_eq!(answer.status, StatusCode::OK);
        assert_eq!(
            answer.json()["versions"]["astroctl"],
            env!("CARGO_PKG_VERSION")
        );
    }

    /// The whole point of the seam: the shell loads with no credential at all, on a node that
    /// requires one for everything else.
    #[tokio::test]
    async fn the_shell_is_served_without_a_token() {
        let node = TestNode::authenticated("s3cret");
        let answer = get(&node, "/", None).await;
        assert_eq!(answer.status, StatusCode::OK);
        assert!(
            answer.content_type.starts_with("text/html"),
            "content-type was {}",
            answer.content_type
        );
        assert!(answer.text().contains("AstroCtl"), "{}", answer.text());
        // Whichever shell this is, a browser must never hold it without asking: it names the
        // hashed asset files, so a cached copy pins the whole application at an old version.
        assert!(
            matches!(answer.cache_control.as_str(), "no-cache" | "no-store"),
            "the shell was served with `{}`",
            answer.cache_control
        );
    }

    /// A path that is neither an asset nor an API route is a client-side route.
    #[tokio::test]
    async fn an_unknown_path_falls_back_to_the_shell() {
        let node = TestNode::authenticated("s3cret");
        for path in ["/target", "/frame/m42", "/stackx"] {
            let answer = get(&node, path, None).await;
            assert_eq!(answer.status, StatusCode::OK, "for {path}");
            assert!(
                answer.content_type.starts_with("text/html"),
                "for {path}: {}",
                answer.content_type
            );
        }
    }

    /// `/stackx` above and `/stack` here: the prefix test is on segment boundaries, or a
    /// client-side route beginning with the same letters would be proxied.
    #[tokio::test]
    async fn the_api_prefix_test_respects_segment_boundaries() {
        assert!(under("/api", "/api"));
        assert!(under("/api/system/health", "/api"));
        assert!(!under("/apiary", "/api"));
        assert!(!under("/", "/api"));
        assert!(under("/stack", "/stack"));
        assert!(!under("/stackx", "/stack"));
    }

    #[tokio::test]
    async fn a_post_to_a_shell_path_is_not_answered_with_html() {
        let node = TestNode::authenticated("s3cret");
        let answer = call(&node, Method::POST, "/target", None).await;
        assert_eq!(answer.status, StatusCode::NOT_FOUND);
        assert_eq!(answer.json()["code"], "NOT_FOUND");
    }

    // --- the embedded bundle ------------------------------------------------------------

    #[cfg(pwa_embedded)]
    mod embedded {
        use super::*;

        /// Every file in the bundle is reachable at its own path with a plausible media type,
        /// rather than only the two or three a hand-written list would have named.
        #[tokio::test]
        async fn every_embedded_file_is_served_at_its_path() {
            let node = TestNode::authenticated("s3cret");
            let mut checked = 0;
            for file in DIST
                .files()
                .chain(DIST.dirs().flat_map(|dir| dir.files().collect::<Vec<_>>()))
            {
                let path = format!("/{}", file.path().display());
                let answer = get(&node, &path, None).await;
                assert_eq!(answer.status, StatusCode::OK, "for {path}");
                assert_eq!(answer.body.len(), file.contents().len(), "for {path}");
                assert_ne!(
                    answer.content_type, "application/octet-stream",
                    "{path} has no media type in the table"
                );
                checked += 1;
            }
            assert!(checked >= 6, "only {checked} files in the bundle");
        }

        /// The service worker's registration will not survive a bad deploy if the browser is
        /// allowed to hold it, and the manifest has to arrive as a manifest or Chrome never
        /// offers to install (USB-09).
        #[tokio::test]
        async fn the_pwa_entry_points_carry_the_headers_chrome_needs() {
            let node = TestNode::authenticated("s3cret");

            let manifest = get(&node, "/manifest.webmanifest", None).await;
            assert_eq!(manifest.content_type, "application/manifest+json");
            assert_eq!(manifest.cache_control, "no-cache");

            let worker = get(&node, "/sw.js", None).await;
            assert!(worker.content_type.starts_with("text/javascript"));
            assert_eq!(worker.cache_control, "no-cache");

            let shell = get(&node, "/", None).await;
            assert_eq!(shell.cache_control, "no-cache");
        }

        /// Content-hashed assets may be cached forever; nothing else may.
        #[tokio::test]
        async fn hashed_assets_are_immutable() {
            let node = TestNode::authenticated("s3cret");
            let assets = DIST.get_dir("assets").expect("the build emits assets/");
            for file in assets.files() {
                let path = format!("/{}", file.path().display());
                let answer = get(&node, &path, None).await;
                assert_eq!(
                    answer.cache_control, "public, max-age=31536000, immutable",
                    "for {path}"
                );
            }
        }

        #[test]
        fn media_types_and_cache_policy() {
            assert_eq!(content_type("index.html"), "text/html; charset=utf-8");
            assert_eq!(content_type("sw.js"), "text/javascript; charset=utf-8");
            assert_eq!(
                content_type("manifest.webmanifest"),
                "application/manifest+json"
            );
            assert_eq!(content_type("icons/icon-192.png"), "image/png");
            assert_eq!(content_type("LICENSE"), "application/octet-stream");

            assert_eq!(
                cache_control("assets/index-abc123.js"),
                "public, max-age=31536000, immutable"
            );
            assert_eq!(cache_control("sw.js"), "no-cache");
            assert_eq!(cache_control("index.html"), "no-cache");
        }
    }

    // --- no bundle ----------------------------------------------------------------------

    #[cfg(not(pwa_embedded))]
    mod placeholder {
        use super::*;

        /// The acceptance criterion "cargo build succeeds with frontend/dist deleted" is only
        /// half the requirement; the other half is that the resulting binary explains itself.
        #[tokio::test]
        async fn the_placeholder_names_the_script_that_fixes_it() {
            let node = TestNode::authenticated("s3cret");
            let answer = get(&node, "/", None).await;
            assert_eq!(answer.status, StatusCode::OK);
            assert!(answer.text().contains("scripts/build-frontend.sh"));
            // The API is emphatically not degraded, and the page says so.
            assert!(answer.text().contains("/api/system/health"));
        }
    }

    /// A node running under the SDD §4.5 loopback exception serves both subtrees with no token,
    /// including the API misses — there is no credential to be wrong.
    #[tokio::test]
    async fn an_open_loopback_node_serves_the_shell_and_a_plain_404() {
        let node = TestNode::open_loopback();
        assert_eq!(get(&node, "/", None).await.status, StatusCode::OK);

        let answer = get(&node, "/api/nope", None).await;
        assert_eq!(answer.status, StatusCode::NOT_FOUND);
        assert_eq!(answer.json()["code"], "NOT_FOUND");
    }

    /// The 401 the fallback renders must be the one the middleware renders, challenge header and
    /// all — the module docs claim they are identical by construction, so this checks it.
    #[tokio::test]
    async fn the_fallbacks_401_is_the_middlewares_401() {
        let node = TestNode::authenticated("s3cret");
        let (router, declarations) = api::router();
        let state = state_with(&node, declarations);
        let app = crate::assemble(router, state);

        let mut responses = Vec::new();
        for path in ["/api/system/health", "/api/undeclared"] {
            let response = app
                .clone()
                .oneshot(
                    Request::builder()
                        .uri(path)
                        .header(header::AUTHORIZATION, HeaderValue::from_static("Bearer no"))
                        .body(Body::empty())
                        .expect("request builds"),
                )
                .await
                .expect("router responds");
            assert_eq!(response.status(), StatusCode::UNAUTHORIZED, "for {path}");
            responses.push((
                response
                    .headers()
                    .get(header::WWW_AUTHENTICATE)
                    .cloned()
                    .expect("RFC 6750 §3 challenge"),
                to_bytes(response.into_body(), 1 << 20)
                    .await
                    .expect("body reads"),
            ));
        }
        assert_eq!(responses[0], responses[1]);
    }
}
