//! Decides whether this build has a PWA bundle to embed — M0-T06.
//!
//! `include_dir!` is a compile-time macro over a real directory: if `frontend/dist` is absent the
//! macro fails, and the crate does not build. That is unacceptable here, because `frontend/dist`
//! is generated by npm and git-ignored, so a fresh clone has none — and a Rust-only contributor
//! must never be blocked on a Node toolchain to run `cargo test`.
//!
//! So the decision is made here instead: this script sets `cfg(pwa_embedded)` when a bundle is
//! present, and `pwa.rs` compiles either the embedded tree or a page telling the reader to run
//! `scripts/build-frontend.sh`. The two paths serve different content but the same routes, so
//! nothing downstream branches on it.
//!
//! It keys off `index.html` rather than the directory, because a directory can exist and be empty
//! — an interrupted build, or `rm -rf frontend/dist/*` — and embedding an empty tree would produce
//! a binary that serves 404 at `/` with no explanation of why.

use std::path::Path;

fn main() {
    // Without this, rustc 1.80+ warns `unexpected cfg condition name` on every build.
    println!("cargo::rustc-check-cfg=cfg(pwa_embedded)");

    let dist = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../frontend/dist");

    // Watch the directory so a rebuild of the bundle is picked up, and `index.html` so *creating*
    // the bundle is too: cargo does not re-run this script when a path it was told to watch comes
    // into existence unless that exact path was named.
    //
    // Cargo compares mtimes, so this notices a bundle that is newer than the last build and a
    // bundle that has been deleted — the two things that actually happen. It does not notice a
    // bundle restored from a backup with an older mtime; `touch frontend/dist/index.html` is the
    // remedy, and the symptom is the placeholder page, which says what to do.
    println!("cargo::rerun-if-changed=../../frontend/dist");
    println!("cargo::rerun-if-changed=../../frontend/dist/index.html");

    if dist.join("index.html").is_file() {
        println!("cargo::rustc-cfg=pwa_embedded");
    }

    // No `cargo::warning` for the absent case. Building the API without the UI is a normal thing
    // to do — every `cargo test` in a fresh clone does it — and a warning on a normal state is
    // how a build teaches people to skim past its output. The placeholder page says what is
    // missing, in the browser, which is where somebody who cares is standing.
}
